//= "../blocks/menu/menu.js"
//= "../blocks/vh-check/vh-check.js"
//= "../blocks/program/program.js"
//= "../blocks/gallery/gallery.js"
//= "../blocks/write/write.js"
//= "../blocks/instagram/instagram.js"
//= "../blocks/reviews/reviews.js"
